# Generated by Django 5.2.4 on 2026-01-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='last_saved_code',
            new_name='code',
        ),
    ]
