# Generated by Django 5.2.4 on 2026-01-22 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_rename_last_saved_code_workspace_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
