# Generated by Django 5.2.4 on 2026-01-22 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_name_alter_workspace_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedworkspace',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('collaborator', 'Collaborator')], default='owner', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(default='Untitled Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
