# Generated by Django 5.2.4 on 2026-01-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_savedworkspace_role_alter_workspace_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='language',
            field=models.CharField(default='javascript', max_length=20),
        ),
    ]
